name: Test

on:
  push:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

env:
  VOICEVOX_ENGINE_REPO: "SHAREVOX/sharevox_engine"
  VOICEVOX_ENGINE_VERSION: "0.2.0"

defaults:
  run:
    shell: bash

jobs:
  # ビルドのテスト
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - run: yarn electron:build_pnever

  # unit テスト
  unit-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - run: yarn test:unit

  # e2e テスト
  e2e-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            voicevox_engine_asset_name: linux-cpu
          - os: macos-latest
            voicevox_engine_asset_name: macos-x64
          - os: windows-latest
            voicevox_engine_asset_name: windows-cpu
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Install xvfb and x11-xserver-utils
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-xserver-utils # for electron
          sudo apt-get install -y libsndfile1 # for engine

      - name: Download VOICEVOX ENGINE
        id: download-engine
        uses: ./.github/actions/download-engine
        with:
          repo: ${{ env.VOICEVOX_ENGINE_REPO }}
          version: ${{ env.VOICEVOX_ENGINE_VERSION }}
          dest: ${{ github.workspace }}/voicevox_engine
          target: ${{ matrix.voicevox_engine_asset_name }}

      - name: Setup
        run: |
          # playwright
          npx playwright install

          # run.exe
          chmod +x ${{ steps.download-engine.outputs.run_path }}

          # .env
          cp .env.test .env
          sed -i -e 's|"../voicevox_engine/run.exe"|"${{ steps.download-engine.outputs.run_path }}"|' .env
          sed -i -e 's|"executionArgs": \[\],|"executionArgs": ["--port=50021"],|' .env

      - name: Run yarn test:browser-e2e
        run: |
          if [ -n "${{ runner.debug }}" ]; then
            export DEBUG="pw:browser*"
          fi
          if [[ ${{ matrix.os }} == ubuntu-* ]]; then
            xvfb-run --auto-servernum yarn test:browser-e2e
          else
            yarn test:browser-e2e
          fi

      - name: Run yarn test:electron-e2e
        run: |
          if [ -n "${{ runner.debug }}" ]; then
            export DEBUG="pw:browser*"
          fi
          if [[ ${{ matrix.os }} == ubuntu-* ]]; then
            xvfb-run --auto-servernum yarn test:electron-e2e
          else
            yarn test:electron-e2e
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Disallowed licenses check
        run: yarn license:generate -- -o sharevox_licenses.json

      - run: yarn typecheck
      - run: yarn lint
      - run: yarn markdownlint
